server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
  ssl:
    bundle: server
  http2:
    enabled: true
  port: 8443

spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: myserver
            password: changeit
          keystore:
            location: classpath:server-keystore.p12
            password: changeit
            type: PKCS12